<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>Painter SVG</title>
    <meta name="description" content="Module JS1 - Exercice Icons">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link href="./css/lib/normalize.css" rel="stylesheet">
    <link href="./css/lib/layout.css" rel="stylesheet">
    <link href="./css/lib/theme.css" rel="stylesheet">
  </head>
  <body>
    <header class="banner">
      <a class="banner-link" href="./">
        <strong class="banner-title">Painter SVG</strong>
        <small>Avec PHP et en POO !</small>
      </a>
    </header>
  
    <main class="project container">
      <!--<svg width=" 200" height="250">

      <rect x="20" y="10" width="30" height="30" stroke="black" fill="transparent" stroke-width="5"/>
      <rect x="30" y="110" width="100" height="40" stroke="silver" fill="darkgoldenrod" stroke-width="10"/>
      <circle cx="50" cy="75" r="20" stroke="red" fill="transparent" stroke-width="5"/>
      <ellipse cx="100" cy="75" rx="20" ry="5" stroke="purple" fill="transparent" stroke-width="5"/>
      <polygon points="200,50 63,400 500,250" />
      
      </svg> -->

      <svg width="1024" height="768">
      <?= $svg ?>
      </svg>      
      <!--svg height="210" width="500">
     <polygon points="100,10 40,198 190,78 10,78 160,198"
    style="fill:lime;stroke:purple;stroke-width:5;fill-rule:evenodd;" />
    </svg> -->     

    </main>

    <footer id="mentions" class="mentions">
      <p><strong> &copy; Olivier Meunier - Tous&nbsp;droits&nbsp;réservés</strong>
    </footer>

    <!-- Affichage du support -->
    <script src=".resources/js/resources.js" data-md=".resources/statement.md"></script>

  </body>
</html>
